package responses

// GenerateTextResponse defines the response for text generation
// @Description Response containing the generated text from the AI
type GenerateTextResponse struct {
	// The generated text content
	// example: "Bits and bytes in endless flow,\nBuilding worlds that softly grow.\nLogic woven, patterns tight,\nCreating order out of night."
	Text string `json:"text"`
}

// GenerateStructuredResponse is a generic map response for structured data
// @Description Response containing structured data generated by the AI
type GenerateStructuredResponse map[string]interface{}

// AiRecommendationResponse defines the response for AI content recommendations
// @Description Response containing AI-powered content recommendations
type AiRecommendationResponse struct {
	// List of recommended items
	Items []map[string]interface{} `json:"items"`
}

// AiContentAnalysisResponse defines the response for AI content analysis
// @Description Response containing AI-powered content analysis
type AiContentAnalysisResponse struct {
	// Analysis results
	Analysis map[string]interface{} `json:"analysis"`
}

// ConversationResponse defines the response for starting a new conversation
// @Description Response containing conversation details
type ConversationResponse struct {
	// Unique ID for the conversation
	// example: conv-123-abcdef
	ConversationID string `json:"conversationId"`
	
	// Initial greeting or message from the AI
	// example: "Hi there! I'm your movie recommendation assistant. What kind of movies do you enjoy watching?"
	Welcome string `json:"welcome"`
	
	// Additional information about the conversation context
	// example: {"contentType": "movie", "session": "active"}
	Context map[string]interface{} `json:"context,omitempty"`
}

// ConversationMessageResponse defines the response to a conversation message
// @Description Response to a message in an AI conversation
type ConversationMessageResponse struct {
	// The AI's response to the user message
	// example: "Based on your interest in Interstellar, I'd recommend checking out these sci-fi movies with similar themes of space exploration and time: 1. Arrival (2016), 2. The Martian (2015), 3. Ad Astra (2019). Would you like more recommendations or details about any of these?"
	Message string `json:"message"`
	
	// Recommendations included in the response, if any
	// example: [{"title": "Arrival", "year": 2016, "genre": "Sci-Fi"}, {"title": "The Martian", "year": 2015, "genre": "Sci-Fi"}]
	Recommendations []map[string]interface{} `json:"recommendations,omitempty"`
	
	// Additional message context
	// example: {"sentiment": "positive", "topicShift": false}
	Context map[string]interface{} `json:"context,omitempty"`
}