###
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@dev.com",
  "password": "TestPassword123"
}

###
# @name getAllClients
# Get all clients to find their IDs
GET http://localhost:8080/api/v1/clients
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name getEmbyClients
GET http://localhost:8080/api/v1/clients/emby
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name getJellyfinClients
GET http://localhost:8080/api/v1/clients/jellyfin
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name getPlexClients
GET http://localhost:8080/api/v1/clients/plex
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name getSubsonicClients
GET http://localhost:8080/api/v1/clients/subsonic
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name setUpSubsonicMusicSync
# Setup movie sync from Plex
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "clientType": "subsonic",
  "syncType": "music",
  "frequency": "daily"
}

###
# @name setUpEmbyMovieSync
# Setup movie sync from Emby
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "clientType": "emby",
  "syncType": "movies",
  "frequency": "daily"
}

###
# @name setUpJellyfinMovieSync
# Setup movie sync from Jellyfin
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "clientType": "jellyfin",
  "syncType": "movies",
  "frequency": "daily"
}

###
# @name setUpPlexMovieSync
# Setup movie sync from Plex
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "clientType": "plex",
  "syncType": "movie",
  "frequency": "daily"
}


###
# @name runEmbyMovieSync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "movies"
}

###
# @name checkJobProgress
# Check if the job is running
GET http://localhost:8080/api/v1/jobs/runs?limit=1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name runJellyfinMovieSync
# Run Jellyfin movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "syncType": "movies"
}

###
# @name runPlexMovieSync
# Run Plex movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "syncType": "movies"
}

###
# @name getMediaSyncJobs
# Get all configured media sync jobs
GET http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name runEmbySeriesSync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "series"
}


###
# @name runEmbyMusicSync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "music"
}

###
# @name runSubsonicMusicSync
# Run Subsonic movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "syncType": "music"
}

###
# @name setUpEmbyHistorySync
# Setup movie sync from Emby
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "clientType": "emby",
  "syncType": "history",
  "frequency": "daily"
}

###
# @name setUpJellyfinHistorySync
# Setup movie sync from Jellyfin
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "clientType": "jellyfin",
  "syncType": "history",
  "frequency": "daily"
}

###
# @name setUpPlexHistorySync
# Setup movie sync from Plex
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "clientType": "plex",
  "syncType": "history",
  "frequency": "daily"
}


###
# @name setUpSubsonicHistorySync
# Setup movie sync from Subsonic
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "clientType": "subsonic",
  "syncType": "history",
  "frequency": "daily"
}

###
# @name runEmbyHistorySync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "history"
}


###
# @name runJellyfinHistorySync
# Run Jellyfin movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "syncType": "history"
}

###
# @name runPlexHistorySync
# Run Plex movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "syncType": "history"
}


###
# @name runSubsonicHistorySync
# Run Subsonic movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "syncType": "history"
}


###
# @name setUpEmbyPlaylistSync
# Setup movie sync from Emby
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "clientType": "emby",
  "syncType": "playlists",
  "frequency": "daily"
}

###
# @name setUpJellyfinPlaylistSync
# Setup movie sync from Jellyfin
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "clientType": "jellyfin",
  "syncType": "playlists",
  "frequency": "daily"
}

###
# @name setUpPlexPlaylistSync
# Setup movie sync from Plex
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "clientType": "plex",
  "syncType": "playlists",
  "frequency": "daily"
}

###
# @name setUpSubsonicPlaylistSync
# Setup movie sync from Subsonic
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "clientType": "subsonic",
  "syncType": "playlists",
  "frequency": "daily"
}


###
# @name runEmbyPlaylistSync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "playlists"
}

###
# @name runJellyfinPlaylistSync
# Run Jellyfin movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "syncType": "playlists"
}

###
# @name runPlexPlaylistSync
# Run Plex movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "syncType": "playlists"
}

###
# @name runSubsonicPlaylistSync
# Run Subsonic movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "syncType": "playlists"
}

###
# @name setUpEmbyCollectionSync
# Setup movie sync from Emby
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "clientType": "emby",
  "syncType": "collections",
  "frequency": "daily"
}

###
# @name setUpJellyfinCollectionSync
# Setup movie sync from Jellyfin
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "clientType": "jellyfin",
  "syncType": "collections",
  "frequency": "daily"
}

###
# @name setUpPlexCollectionSync
# Setup movie sync from Plex
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "clientType": "plex",
  "syncType": "collections",
  "frequency": "daily"
}


###
# @name setUpSubsonicCollectionSync
# Setup movie sync from Subsonic
POST http://localhost:8080/api/v1/jobs/media-sync
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "clientType": "subsonic",
  "syncType": "collections",
  "frequency": "daily"
}


###
# @name runEmbyCollectionSync
# Run Emby movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getEmbyClients.response.body.$.data[0].id}},
  "syncType": "collections"
}


###
# @name runJellyfinCollectionSync
# Run Jellyfin movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getJellyfinClients.response.body.$.data[0].id}},
  "syncType": "collections"
}

###
# @name runPlexCollectionSync
# Run Plex movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getPlexClients.response.body.$.data[0].id}},
  "syncType": "collections"
}

###
# @name runSubsonicCollectionSync
# Run Subsonic movie sync manually
POST http://localhost:8080/api/v1/jobs/media-sync/run
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "clientID": {{getSubsonicClients.response.body.$.data[0].id}},
  "syncType": "collections"
}
