###
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@dev.com",
  "password": "TestPassword123"
}

### Validate session
GET http://localhost:8080/api/v1/auth/validate
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name embyClient
POST http://localhost:8080/api/v1/admin/client/emby
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "name": "Emby",
  "clientType": "emby",
  "isEnabled": true,
  "client": {
    "baseURL": "{{EMBY_TEST_URL}}",
    "apiKey": "{{EMBY_TEST_API_KEY}}",
    "username": "{{EMBY_TEST_USER}}",
    "ssl": false
  }
}

###
# @name GetMovieByIDFromClient
GET http://localhost:8080/api/v1/client/{{embyClient.response.body.$.data.id}}/movie/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

###
# @name TestConnection
GET http://localhost:8080/api/v1/client/{{embyClient.response.body.$.data.id}}/test
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}
